In [ ]:
! pip install -U -q gensim

In [ ]:
import numpy as np
from scipy.spatial.distance import pdist,squareform

from gensim.models.word2vec import LineSentence
from gensim.models.fasttext import FastText
from gensim.models.doc2vec import Doc2Vec, TaggedLineDocument

In [ ]:
by_repo = LineSentence('./prepared-readmes/by_repo_no_sentence.txt')
by_repo_doc = TaggedLineDocument('./prepared-readmes/by_repo_no_sentence.txt')

In [7]:
d2v = Doc2Vec(vector_size=100, min_count=20, window=10, epochs=5, workers=7, dbow_words=1)
d2v.build_vocab(by_repo_doc)

In [ ]:
d2v.train(by_repo_doc, total_examples=d2v.corpus_count, epochs=d2v.epochs)

In [150]:
with open('./ss/eye.txt', 'r') as f:
    foo = [l.strip().split(' ') for i,l in enumerate(f)]

vecs = [d2v.infer_vector(s) for s in foo]

squareform(pdist(np.array(vecs), 'cosine'))

array([[0.        , 0.41102515, 0.03342422, 0.03764876, 0.06420119],
       [0.41102515, 0.        , 0.37910537, 0.39696009, 0.42604322],
       [0.03342422, 0.37910537, 0.        , 0.0458939 , 0.08013899],
       [0.03764876, 0.39696009, 0.0458939 , 0.        , 0.0745646 ],
       [0.06420119, 0.42604322, 0.08013899, 0.0745646 , 0.        ]])

In [90]:
[' '.join(s) for s in foo]

['This is a deep learning library designed for efficient training on super large dataset',
 'Repository for all the Pearl code that I never wrote.',
 'A matrix algebra library for Tensorflow. Written to take advantage of BLAS and GPU accelerated machines',
 'A classification algorithm designed for multi-class classification on high-dimensional data',
 'This is a nodejs stream utility library, designed for modular use in your node app']

In [153]:
def get_vector(s):
    try:
        return d2v.wv.get_vector(s)
    except KeyError:
        return None

avg_vecs = [np.array([get_vector(s) for s in sent if get_vector(s) is not None]).mean(0) for sent in foo]

squareform(pdist(avg_vecs, 'cosine'))

array([[0.        , 0.39126802, 0.26274414, 0.18139755, 0.22882877],
       [0.39126802, 0.        , 0.40214265, 0.49948562, 0.28766898],
       [0.26274414, 0.40214265, 0.        , 0.39020288, 0.36230746],
       [0.18139755, 0.49948562, 0.39020288, 0.        , 0.40054336],
       [0.22882877, 0.28766898, 0.36230746, 0.40054336, 0.        ]])

In [128]:
d2v.wv.distances('javascript', ['python', 'java', 'matlab', 'stata', 'spss'])

array([0.7772465 , 0.76168656, 0.97259724, 1.0599113 , 0.9560096 ],
      dtype=float32)

In [136]:
d2v.save('d2v-1')

In [134]:
from gensim.models import FastText
ft = FastText(size=100, min_count=10, window=10, sg=1, epochs=5, workers=7)

ft.build_vocab(by_repo_doc)
ft.train(by_repo_doc, total_examples=ft.corpus_count, epochs=ft.epochs)
ft.save('ft/2/ft2')

NotImplementedError: Supervised fastText models are not supported